### ISSUE TITLE
Correct links for YLE live streams

### ISSUE THREAD

**Issue by Laucha** [finnhubb/plugin.video.areena#1]
Hi,

Here the correct links for the live streams.
YLE TV1 https://yletv.akamaized.net/hls/live/622365/yletv1fin/master.m3u8
YLE TV2 https://yletv.akamaized.net/hls/live/622366/yletv2fin/master.m3u8
YLE TEEMA/FEM https://yletv.akamaized.net/hls/live/622367/yletvteemafemfin/master.m3u8

Sorry if I didn't post in good place.

Greetings!

**Comment by Mateus109** [comment]
@Laucha thanks for posting but I don't think those links work outside of Finland.

**Comment by Laucha** [comment]
@Mateus109 Actually, their are only for Finland.

**Comment by finnhubb** [comment]
Hi,

@Laucha 
Thank you for providing new links. I have used them in release v1.1.0. 

In future when you open issue it is helpful to provide extra info. For example, say why these links are "correct". Old links were still playing video, so it was not obvious there was a problem.

@Mateus109 
Thanks for replying. It should work now in latest release.

Enjoy!

**Comment by Mateus109** [comment]
Only within Finland; it seems Yle are no longer live stream outside of Finland using the new or old m3u8 links.

**Comment by finnhubb** [comment]
@Mateus109
Which platform and kodi version did you test on?
